### ISSUE TITLE
Bios Unreadable

### ISSUE THREAD

**Issue by Llorean** [Mazamars312/Analogue_Pocket_Neogeo#12]
With the suggest BIOS, in some games the options are not readable.
![20220814_175910](https://user-images.githubusercontent.com/11658195/184559137-4b5faf10-c0b6-4da0-b45b-0e08dbcd5d06.jpg)
When an option is toggled or changed, it's clear something is changing (vague collections of white pixels appear, not enough necessarily to tell what shape they represent) but it's more or less impossible to tell what I'm setting the values to.

**Comment by Mazamars312** [comment]
Can you show which bios, game and game files you are using. as Metal slug 5 works for myself on the uni-bios_1_0.rom.

Then i can back look at this

**Comment by Llorean** [comment]
I'm using the uni-bios_1_0.rom with the Darksoft set.

The md5sum of the .rom is 6293999bbc32e594aa0ae1da2113dc4d
I get the same results with Metal Slug 5 if I choose the normal version or the AES version.

**Comment by Mazamars312** [comment]
Oh I see it now. Let me have a look. Might be a sfix issue that ill need to look at.

**Comment by Mazamars312** [comment]
Confirmed this is the sfix I need to fixup. This will be in the next build I do. Please give me some time on this, but thank you for showing this.

**Comment by Mazamars312** [comment]
This should be fixed now in 0.7.5 as I have also added the sfix.sfix from to the system. Please enjoy
