### ISSUE TITLE
Neo Turf Masters - gaps in UI sprites

### ISSUE THREAD

**Issue by itsTrifle** [Mazamars312/Analogue_Pocket_Neogeo#14]
Some gaps in UI sprites can be seen in the player banner that appears at the start of the turn and around the shot power gauge - see the arrow at 50% and the low/nice/high labels.
Does not appear in the current MiSTer core.
Pocket 
![image](https://user-images.githubusercontent.com/66260971/184635572-bda704ef-8a51-4f38-92cf-cbf70d99cf4d.jpeg)
Mister NeoGeo 20220403
![image](https://user-images.githubusercontent.com/66260971/184635640-2a1eaa0a-9ba1-4270-88b4-8ec8ac19f10f.jpeg)

**Comment by Mazamars312** [comment]
Will look into this after moving the ram around in the core.

**Comment by Mazamars312** [comment]
This has been partly fixed now... BUT I need someone to fully check in 0.7.5 please

**Comment by itsTrifle** [comment]
This seems to be fixed in the 0.7.5 release as far as I can tell - at least the examples I reported initially
