### ISSUE TITLE
Metal Slug X - Text Flicker during the End Credits

### ISSUE THREAD

**Issue by OngoGablogian** [Mazamars312/Analogue_Pocket_Neogeo#17]
Thanks so much for your work on the core! Just noticed some text flickering during the credits on Metal Slug X and thought I should report it.

https://user-images.githubusercontent.com/18250317/184710277-9c2cb57d-21a8-464a-bda6-ccbb6a03f985.mp4

**Comment by Mazamars312** [comment]
Once I have done the larger games Ill look into this and the other offset issue with some games.

**Comment by Mazamars312** [comment]
Is this still haplening now with version 0m8.1?

**Comment by terminator2k2** [comment]
seems ok now this one

**Comment by Mazamars312** [comment]
Sweet closing off
