### ISSUE TITLE
Access to BIOS settings

### ISSUE THREAD

**Issue by hiddenindians** [Mazamars312/Analogue_Pocket_Neogeo#18]
With version 0.5, I was able to set the BIOS options (region/mode) before a game started. With 0.6, Games are defaulting to USA/CONSOLE and I can't seem to change this. Is there anyway to configure the BIOS with 0.6?

**Comment by JonAbrams** [comment]
Try holding B+X+Y then press L.

**Comment by Mazamars312** [comment]
This is a BIOS access. You can do as Jon says and access the BIOS that way
