### ISSUE TITLE
Unable to Set Slot 1 Soft Dip Switches in Metal Slug 2/2 Turbo

### ISSUE THREAD

**Issue by dji85** [Mazamars312/Analogue_Pocket_Neogeo#22]
When accessing the soft dips for Metal Slug 2/2 Turbo the Slot 1 software selection appears in garbled text, and the settings are unable to be changed.

**Comment by Mazamars312** [comment]
This is addressed in another issue. this is due to the SFIX and SROM roms that both need to be loaded and will be coming out on the next build
