### ISSUE TITLE
Analogue OS v1.1 beta 2

### ISSUE THREAD

**Issue by mddifilippo89** [Mazamars312/Analogue_Pocket_Neogeo#23]
[Request] Add compatibility for the new beta.

**Comment by JonAbrams** [comment]
It works for me with uni-bios_1_0.rom

**Comment by mddifilippo89** [comment]
Baseball Stars 2? I haven't got a single game working since the update. With uni bios 1.0 or 4.0

**Comment by mddifilippo89** [comment]
Going back to bios 1.0, USA (CONSOLE) worked for me.

-------

The root issue is using bios 4.0, USA (Arcade)

**Comment by mddifilippo89** [comment]
Workaround for Bios 4.0 - dip switch 0 in core options (analogue pocket menu after booting game and screen goes black)

**Comment by VideogameScrapbook** [comment]
I tried a Unibios 1.0 (I believe MVS though) and it doesn't work. What's the checksum of the AES BIOS you are using?

And to developers: I suggest authors of Analogue Pocket cores always share checksum of recommended BIOS to allow for consistency when testing.

**Comment by VideogameScrapbook** [comment]
I was able to get Unibios 1.0 working (CRC-32: 0ce453a0) without setting the dipswitch. Press A+B+C as soon as you see unibios splash screen to change its settings. Then use American console for settings. If you want to use a different region, you can set dipswitch 0 as explained earlier, but you have to do it every time, unlike the American console option which doesn't require going into menu every time after first setup.

**Comment by JackWitherell** [comment]
I know someone will come here looking for fixes/short term workarounds.
![image](https://user-images.githubusercontent.com/4626546/188572664-71f5618f-202f-4366-99c8-6e866934b669.png)

**Comment by Mazamars312** [comment]
I have removed the Dipswitch in version 0.7.5 for now to help resolve this issue. I will look into this more when I get the time in 0.8.0
