### ISSUE TITLE
Rename sfix.sfix

### ISSUE THREAD

**Issue by owlnonymous** [Mazamars312/Analogue_Pocket_Neogeo#26]
The core is looking for "sfix.sfix", where the original file is named "sfix.sfx". Renaming sfix.sfx to sfix.sfix got the core running for me. This is reflected in your README.md and Core.

**Comment by Mazamars312** [comment]
Weird. My list of files says sfix. I'll add an exception in the data.json to look for both but the default will be sfix.sfix

I hate that there are so many different file names for the same file.

**Comment by owlnonymous** [comment]
The original file is called "sfix.sfx", but in the old code I think it looked for "sfix.sfix" instead. Probably just a simple mistake. Thanks for the update!

**Comment by Mazamars312** [comment]
NP. thanks
