### ISSUE TITLE
Distorted audio in "The Super Spy"

### ISSUE THREAD

**Issue by naveedster** [Mazamars312/Analogue_Pocket_Neogeo#28]
As soon as the user loads up The Super Spy, distorted audio is heard throughout the intro and in gameplay.

**Comment by naveedster** [comment]
https://user-images.githubusercontent.com/80052032/190948046-1088cda1-fcad-40d6-bd50-1394e7138791.MOV

strangely turning the system off and playing it again fixed this issue! Still it is a bug.

**Comment by naveedster** [comment]
There is also still popping and cracking audio for this game.

**Comment by naveedster** [comment]
Here is what it sounded like the first few times I tried to play it: https://youtube.com/shorts/fD2NgV1LrEY?feature=share

**Comment by Mazamars312** [comment]
Ill look into this once I get more of the Graphics sorted on this core first

**Comment by Krathoon** [comment]
This also happens in Blazing Star and Metal Slug 3. It is happening all over. There is an audio bug in there.

**Comment by Mazamars312** [comment]
Found the issue to be a masking issue. working on this and a few other things at this moment

**Comment by Mazamars312** [comment]
Resolved in 0.8.0, this was due to a masking and offset issue with the VROMS
