### ISSUE TITLE
Xenocrisis MiSTer version "too large"

### ISSUE THREAD

**Issue by Llorean** [Mazamars312/Analogue_Pocket_Neogeo#29]
The larger Xenocrisis ROM still doesn't load, with an error message indicating it's too large. I know it's not one of the original NeoGeo ROMs so it isn't necessarily expected to work based on the readme, just wanted to document it here.

**Comment by Mazamars312** [comment]
I will be making a special build for this due to the stereo sound requiring about 32mbytes of data. as the audio is currently limited to 16mbytes of data.
