### ISSUE TITLE
BIOS setting not saving after power-off

### ISSUE THREAD

**Issue by t3rminus** [Mazamars312/Analogue_Pocket_Neogeo#30]
Steps to reproduce:
1. Access BIOS settings during boot by holding A+B+C
2. Change region/mode to USA/Console
3. Wait for game to start. Play for a while.
4. Press "Home" button to return to the menu. Choose "Quit"
5. Power off Analogue Pocket by holding power button until the console shuts down
6. Power on console by holding power button
7. Launch the same ROM

Expected:
BIOS region/mode remains the same

What happens:
BIOS region/mode is reset to Europe/Arcade

**Comment by Mazamars312** [comment]
Fixed in version 0.8.0
