### ISSUE TITLE
Slow Downs on Super Sidekicks/Street Hoop with V0.7.5

### ISSUE THREAD

**Issue by alesgarci** [Mazamars312/Analogue_Pocket_Neogeo#33]
With V0.6.0 there is no slow down in the game. Once i updated to v0.7.5 in order to be compatible with new analogue pocket firmware, heavy slow downs in this game.

Thank you very much for your effort and this neo geo core for the analogue pocket

**Comment by Mazamars312** [comment]
Yes, Ive had to re-write the whole memory controllers. The next build I will be looking at speeding this up.

**Comment by timotheeg** [comment]
I just received my Pocket and I see some slow downs in the various metal slugs too (on 0.7.5), and I was wondering if the Pocket just wasn't powerful enough to run the NeoGeo 😢.  But so we can expect speed improvements in the future?

**Comment by davewongillies** [comment]
> I just received my Pocket and I see some slow downs in the various metal slugs too (on 0.7.5), and I was wondering if the Pocket just wasn't powerful enough to run the NeoGeo cry. But so we can expect speed improvements in the future?

https://twitter.com/UFp64/status/1610764434464739328

**Comment by timotheeg** [comment]
Thanks for that link @davewongillies 🙏

**Comment by Mazamars312** [comment]
Slowdowns have been reduced a lot in version 0.8.0 being release this weekend
