### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by Princepicklepants** [Mazamars312/Analogue_Pocket_Neogeo#34]
Core is amazing whole family is having the best time playing through these great arcade games , is it possible to move the reset game button to a menu option. My nephews are playing through the  metal slugs and keep hitting the shoulder button equivalent on the 8bitdo arcade stick and resetting the game. I know it’s user error and most people won’t do that but it would make a big difference to these young guys!

**Comment by Mazamars312** [comment]
As the Neogeo core is in beta I have keep this on for now. Will look at making a option to disable this.

**Comment by Princepicklepants** [comment]
That would be great thank you! Looking forward to the next update

**Comment by Wabbajackw** [comment]
Same here, after a long session i reset by accident in final mission...

**Comment by tarikalmashni** [comment]
> is it possible to move the reset game button to a menu option.
I literally came here just to ask the same. But I'm glad it's already covered here and the dev is already (eventually) planning to do it after leaving beta. (I'd still love to have this earlier though honestly)

**Comment by Princepicklepants** [comment]
Awesome thanks!
