### ISSUE TITLE
Bad Apple demo - possible to get working?

### ISSUE THREAD

**Issue by ghamson** [Mazamars312/Analogue_Pocket_Neogeo#35]
Hi,

I've been trying to get the Bad Apple demo working on the Analogue Pocket but despite trying to setup the JSON files, I have had no luck.

Do you know if it is supported and it so, how I would go about trying it out?

Cheers

Giles

**Comment by Mazamars312** [comment]
No ass the CROM I believe is about 128mbytes which the Analogue pocket does not have.

This is why I have said that Homebrews are not fully supported.

**Comment by ghamson** [comment]
Thanks for the reply and no worries - very much appreciated and thanks for all the work on this core... I love playing FPGA Neo Geo on the pocket!

**Comment by Mazamars312** [comment]
Thanks
