### ISSUE TITLE
I get error like this. 

### ISSUE THREAD

**Issue by Mika73** [Mazamars312/Analogue_Pocket_Neogeo#37]
![81546F15-A5D5-448F-A2D8-28C7CE503862](https://user-images.githubusercontent.com/12106091/202541425-a93fd889-4e85-4574-8288-b9cf07500836.jpeg)

**Comment by Mika73** [comment]
Thank you. I try find another roms. Got these zipped Neo Geo ROMS with Anbernic 351MP. 

Lähetetty iPhonesta

**Comment by terminator2k2** [comment]
you need to darksoft rom set unzipped
