### ISSUE TITLE
Blues Journey distorted sound......(real bad)

### ISSUE THREAD

**Issue by Wesleyrpg** [Mazamars312/Analogue_Pocket_Neogeo#38]
Just wanted to let you know that Blues Journey has really badly distorted sound on certain sounds, and sound effects

**Comment by Mazamars312** [comment]
Found the issue to be a masking issue. working on this and a few other things at this moment

**Comment by Mazamars312** [comment]
This should be fixed in 0.8.1 can you please confirm

**Comment by Wesleyrpg** [comment]
It was 99% fixed on 0.8.0 with only the slightest pop once in a while......i'll test 0.8.1 tomorrow for you!

**Comment by Mazamars312** [comment]
0.8.1 is more on some masking for graphics, so that's a good sign

**Comment by Wesleyrpg** [comment]
yes, blues journey works well now on the pocket itself.

I'll test with the dock later!

**Comment by Wesleyrpg** [comment]
Didn't get a chance to test it on the dock, but i'm guessing it's fine.....you're welcome to close this!
