### ISSUE TITLE
Core Doesn't support Stereo version of XenoCrisis

### ISSUE THREAD

**Issue by Goldanas** [Mazamars312/Analogue_Pocket_Neogeo#4]
There are 2 versions of the XenoCrisis rom that you get when you purchase from BitMap Bureau:
- A Mono mixed version with everything in one 16 MB vrom
- A Stereo version with a 32 MB vrom (I believe two banked 16 MB roms, concatenated together)

The current version will throw a warning over this 32 MB vrom size, which is probably expected as its abnormal, but there does appear to be a way to implement for proper playback as it has been done via MiSTer.

The original file does have a special parameter to be included with the romset.xml listing for MiSTer, which is: vromb_offset="0x1000000"
The ROM can be officially purchased here:
https://shop.bitmapbureau.com/products/xeno-crisis-neo-geo-aes-mvs-rom-download

**Comment by alexcom84** [comment]
Both versions are stereo, it just has higher quality samples. You’re confusing it with the Xenocrisis cart version with the mono audio bug that required a CPLD and M1/P1 rom update.

**Comment by Goldanas** [comment]
I am not:
https://www.patreon.com/posts/missing-files-60446967

![Screenshot 2022-08-01 142831](https://user-images.githubusercontent.com/67668858/182249835-8b6aec6b-65dc-466d-945c-c641d83fdb37.png)

**Comment by Mazamars312** [comment]
I will need to look into this as I only had the Neogeo made roms and I didnt expect larger VROMS of 16Mbyte and CROMs of over 64Mbytes. 

The Limits of the ram are as follows
CROM: 64Mbytes
VROM: 16Mbyte
PROM 12Mbyte
Z80 Program: 512Kbyte
SFIX: 256Kbytes (This will be increased to 512Kbyte soon)

I will add this as part of the Readme that the High Stereo version will not work at this moment.

**Comment by Goldanas** [comment]
Yeah, it seems like a special case where you'd have to drop it into the sdram along with the small amount of crom this game has as a special exception. Thanks for taking a look.

**Comment by Mazamars312** [comment]
Thanks

**Comment by dji85** [comment]
@Mazamars312 I tried the stereo version on the new core but am still seeing the same issue (Error in framework File ID [7] too large), thanks!

**Comment by eobet** [comment]
Almost two years on, I'm seeing the same issue still unfortunately.
