### ISSUE TITLE
Cannot load Pulstar under Alpha 0.8.0

### ISSUE THREAD

**Issue by Parodius79** [Mazamars312/Analogue_Pocket_Neogeo#46]
Gives message: Error in Framework - File ID (257) too large. 
Using the dark soft romset pak. no issue with other ROMs so far

**Comment by mbaran5** [comment]
Delete your old save file under Saves in SD card root.

**Comment by timotheeg** [comment]
Aye, the fix is documented in the readme [here](https://github.com/Mazamars312/Analogue_Pocket_Neogeo#installation-and-usage) :) 

> * If you have an issue with an error 257 this means that the save files in the "\saves\ng\Mazamars312" folder might need to be deleted as the max size of the saves can be 8Kbytes

**Comment by Mazamars312** [comment]
Yep this is a save game issue. Just remove them from the save folder and you will be back on the core..
