### ISSUE TITLE
Last Hope scrambled graphics

### ISSUE THREAD

**Issue by Kypck** [Mazamars312/Analogue_Pocket_Neogeo#47]
Unfortunately I am not able to get this game to run in a visibly good way. the graphics are always scrambled.
Gameplay/sound seem fine. As the game works good on the MiSTer I would like to know how to assemble the rom?

Do you need to concat the C-Roms out of order?
![20230116_072616](https://user-images.githubusercontent.com/122769703/212605314-e7c9d3d2-0f08-43c7-9710-c8a8118a54ab.png)

**Comment by terminator2k2** [comment]
this game ran ok on 0.7.5

![20230116_195950](https://user-images.githubusercontent.com/48845336/212760770-bd7d6a51-2dd4-46b6-97ae-534e4be29c1c.png)
![20230116_201631](https://user-images.githubusercontent.com/48845336/212760772-341bfd34-801a-4fca-9979-d36fa1bf9021.png)

but has text glitches on 0.8.0

![20230116_202253](https://user-images.githubusercontent.com/48845336/212760844-0022e948-8b09-4f9c-b2e3-8990118c44b5.png)
![20230116_202303](https://user-images.githubusercontent.com/48845336/212760848-1959199a-352d-460c-8d37-62a32229f7ee.png)

**Comment by Mazamars312** [comment]
Found the issue. Most games have an SROM size of 128K, where Last hope has a 64K Rom. 
So I didn't have an edge-case for this.

Will add this to the next update. Or you can double the SROM data twice for the temporary moment.

**Comment by Kypck** [comment]
Works like a charm for the text layer. Thank you very much! 
@terminator2k2 : Any Idea why the graphics are still scrambled on my end? Used 
cat ngdt-300-c1.bin  ngdt-300-c2.bin  ngdt-300-c3.bin  ngdt-300-c4.bin > crom0
to create the crom0

**Comment by terminator2k2** [comment]
use this python script :
https://www.arcade-projects.com/threads/how-to-convert-files-to-work-with-neogeo-multi.24393/
so do c1.bin + c2.bin then c3.bin + c4.bin then concatenate the 2 files together

**Comment by Kypck** [comment]
It just works if you do it right :-)
Thank you very much. I searched for such information (especially knowing about Darksofts work) but did not find any infos. Really appreciate that!

**Comment by Mazamars312** [comment]
Have fixed the SROM mask in0.8.1 and if you used the full crom you should be all good
