### ISSUE TITLE
v0.8.0 controls missing for Pad 2

### ISSUE THREAD

**Issue by nach-code** [Mazamars312/Analogue_Pocket_Neogeo#48]
When going to setup controllers for this core, it's possible to configure which buttons to use for Pad 1. However, if a Pad 2 is connected, there is no way to set up the buttons.

Can the same settings for Pad 1 be exposed for Pad 2?

Thank you.

**Comment by Mazamars312** [comment]
This is a limitation on the APF framework. Im sure they are working on this soon as i did make them aware of it.
