### ISSUE TITLE
Feature: Pause option

### ISSUE THREAD

**Issue by nach-code** [Mazamars312/Analogue_Pocket_Neogeo#49]
Can a pause option be added?

When playing in arcade mode, there's no way to pause the game that's running. Even when bringing up the analogue menu, the game is still running in the background.

**Comment by Mazamars312** [comment]
Nope not in the core, but if you use unibios you can press start and select to pause in software

**Comment by nach-code** [comment]
Bringing up the unibios covers the screen in garbage. So sure, it pauses the game, but then unpausing doesn't work well.
