### ISSUE TITLE
Default Button Mapping Suggestion

### ISSUE THREAD

**Issue by Goldanas** [Mazamars312/Analogue_Pocket_Neogeo#5]
When the user remappable controls become a thing, this may not matter, but I'd recommend adjusting the default button layout to the recently released official SNK Neo Geo pads that came with the MVS Mini and Arcade Stick Pro:
![630804_211045_01_front_zoom](https://user-images.githubusercontent.com/67668858/182260589-9eb89a4b-2d81-4f96-84a5-13a37d9edb3b.jpg)
This would look like this on the Pocket (image by terminator2k2 on Discord):
![analogue_pocket_header](https://user-images.githubusercontent.com/67668858/182260661-5b3ad3ed-1a2e-4925-abe4-b79a35b30530.jpg)

This is an optimal layout for many games. Many fighting games (certainly the most popular) have punches on A and C, and kicks on B and D. For games like Metal Slug and other platforms, action is on A, and jump on B (with a third option on C), and this also works well.

**Comment by Mazamars312** [comment]
The Remapping will be part of the Analogue APF Json file soon. However I will change this for the next release. Adding to the Todo list.

**Comment by RevQuixo** [comment]
![image](https://user-images.githubusercontent.com/36825007/182367312-7a1c06df-5ba1-41a3-b71d-058f958c208f.png)

Personally the official Neo Geo CD pad has a better layout in my opinion.

**Comment by Wabbajackw** [comment]
RevQuixo is right, it's best optimized with the neogeo cd controller, I use it with my Mister for the most authentic experience and it's perfect

**Comment by dji85** [comment]
Agree with @RevQuixo , that way you don't end up with a funky layout when used with the dock and an arcade stick too.

**Comment by VideogameScrapbook** [comment]
Confirmed with Analogue OS v1.1 beta 2 that this works now with newly available Core Settings:
* Player Type 1 = SNES layout (default)
* Player Type 2 = MVS mini
* Player Type 3 = Neo Geo CD

**Comment by JackWitherell** [comment]
changing `"default": "0"` didn't work for me so my workaround (not ideal) for forcing my controller choice in the meantime in `interact.json`:
![image](https://user-images.githubusercontent.com/4626546/188573209-164a33b2-35c0-4953-bdc9-177480d22b6d.png)

**Comment by VideogameScrapbook** [comment]
@JackWitherell, doing that doesn't work for me (or at least when setting min: 1 to select MVS mini layout). When entering the menu, it successfully shows the player type selected based on this modification, but the actual button layout is still the default until pressing A on the setting in the core menu. Then when starting a new game, have to do process again, so it seems better to leave min as 0.

**Comment by JackWitherell** [comment]
Wow, you're entirely right. What a mess.

After messing around a bit more I've solved some of the problems with this.
I've finally gotten it working. Try this:

![image](https://user-images.githubusercontent.com/4626546/188764153-bf06ca1d-8377-4ff2-8473-d611a63b83df.png)

**Comment by Mazamars312** [comment]
I hope the current setup in the interact works for now.
