### ISSUE TITLE
Crossed Swords 2 (CD Conversion) - Glitched graphics and missing lauers

### ISSUE THREAD

**Issue by GumbyXGames** [Mazamars312/Analogue_Pocket_Neogeo#50]
![20230118_154944](https://user-images.githubusercontent.com/82996624/213293005-01497202-3dbd-4520-8fb5-cf80626797d7.jpg)
When playing the NeoGeo conversion of Crossed Swords 2, some sprite layers will flash or disappear completely. The game does not crash even if the video is completely missing or garbled.

Secondary issue is the the game can only be played with the Overdrive core. The standard core errors out with "File ID [257] too large".

Edited to add image of issue
Edit: Forgot to add I did not have this issue with Alpha_0.7.5_2022-19-09

**Comment by GumbyXGames** [comment]
Second image of issue
![20230118_155902](https://user-images.githubusercontent.com/82996624/213293346-0018d054-1960-486a-be1a-f77e7fdfc62a.jpg)

**Comment by mbaran5** [comment]
Error 257 is a result of having an old save file. See here: https://github.com/Mazamars312/Analogue_Pocket_Neogeo/blob/cf1c4c60ce52574a924ec8db14680d567e75d3b3/README.md?plain=1#L39

**Comment by Mazamars312** [comment]
Yep the 257 error is the saves
As to the graphic bugs, which version of the neogeo core are you using? as more was fixed in 0.8.1

**Comment by GumbyXGames** [comment]
> Yep the 257 error is the saves As to the graphic bugs, which version of the neogeo core are you using? as more was fixed in 0.8.1

I'm using 0.8.1. Maybe it's because I used the Overdrive core? Let me delete that save file I didn't know I had and I'll see if it runs better under the normal core.

**Comment by GumbyXGames** [comment]
Deleting the save got the game working with the regular core. With that core there are no graphical issues. Closing issue. Thanks for the help
