### ISSUE TITLE
File size error

### ISSUE THREAD

**Issue by DrAvedi** [Mazamars312/Analogue_Pocket_Neogeo#54]
Been enjoying this core immensely since it's release.

Since updating to 8.1, I'm getting an error when loading a significant number of these Darksoft roms. "Error in framework File ID [257] too large"

Certain roms boot without issue, no error message.

I'm getting the error in too many games to list them all here. A few examples:

2020 Super Baseball
Aero Fighters 2
Fatal Fury
Ghostlop
KoF '94
Mutation Nation

Please help!!

**Comment by DrAvedi** [comment]
oh, i'm using the recommended bios, uni-bios 4.

Thanks

**Comment by mbaran5** [comment]
This is covered in readme. Delete any old saves that are larger than 8kb. 

https://github.com/Mazamars312/Analogue_Pocket_Neogeo#installation-and-usage

* If you have an issue with an error 257 this means that the save files in the "\saves\ng\Mazamars312" folder might need to be deleted as the max size of the saves can be 8Kbytes

**Comment by DrAvedi** [comment]
Oh, thanks. I figured it was my fault for missing some important detail.
