### ISSUE TITLE
Big golf ball sprite appears next to the golfer in Neo Turf Masters

### ISSUE THREAD

**Issue by c0de90e7** [Mazamars312/Analogue_Pocket_Neogeo#55]
Hi,

In Neo Turf Masters ( golf game ) a big golf ball appears on the grass to the left of the golfer. Seems like a scaled or bigger version ( like 7X by 7X the size of the normal ball the golfer hits ) of the ball sprite.

![IMG_20230207_115148](https://user-images.githubusercontent.com/482974/217225140-efecc1e0-11f8-432f-87a6-e7d5cdd398f6.jpg)

Thank you for your amazing work.

**Comment by c0de90e7** [comment]
I apologize for having opened this; strange as it may seem this is actually normal or present in the mame emulated game too, I looked for an original board video but found none. But 99% sure this is not an actual bug now.

**Comment by aphexian** [comment]
Sorry, but I have to laugh. That's what a tee box generally looks like on a golf course - the area between the two markers is where you tee off from.

![IMG_3504](https://github.com/Mazamars312/Analogue_Pocket_Neogeo/assets/72033725/be656d34-1d98-4982-93aa-7e2d3497d060)
