### ISSUE TITLE
Add Jotego to the list of credits

### ISSUE THREAD

**Issue by maspling** [Mazamars312/Analogue_Pocket_Neogeo#6]
As the readme mentions informing you of other devs involved in the initial core that should be mentioned, I noticed that it uses the JT12 and JT49 cores created by  Jose Tejada (@topapate) more commonly known as Jotego. Just thought it was worth mentioning :)

**Comment by Mazamars312** [comment]
I have already added this to my todo list. When I add this and Snog's name as well for the mappers as well when I do the next release.

Most of my work was done in the main core and my own work so I want to make sure everyone is added to the credits here. 

Thanks :-)
