### ISSUE TITLE
Truncated sprites in Blazing Star

### ISSUE THREAD

**Issue by TheOldCamper** [Mazamars312/Analogue_Pocket_Neogeo#66]
I experience occasional truncated sprites and sprite flicker mostly on boss fights
![20240202_113456_Blazing Star boss glitch](https://github.com/Mazamars312/Analogue_Pocket_Neogeo/assets/158571117/1e5f9c71-9117-4ee2-9e98-c084fc1af18e)

Hardware: Analogue Pocket, white (from the Preorder Fulfillment Group C: 2023)
Core: Neo Geo 0.8.1 by Mazamars312
BIOS: uni_bios_4_0
Region: Europe
Mode: Arcade
MVS/AES: Checked (Enabled)

**Comment by Mazamars312** [comment]
Wonder what it could be..... The only thing I can think is that it is a bandwidth issue. unless this happens on real hardware. have we checked this as I do know there is some spritetruncation if a lot is happening on screen.

Could you confirm?

**Comment by Mazamars312** [comment]
https://wiki.neogeodev.org/index.php?title=Sprites_per_line_limit

This holds some information on what could be happening.

**Comment by TheOldCamper** [comment]
Yes thank you, 
Apparently it's happening on real hardware - I never experienced Blazing Star outside emulation so I wasn't expecting this!
Case closed
