### ISSUE TITLE
Audio Layers Missing/Distorted

### ISSUE THREAD

**Issue by dji85** [Mazamars312/Analogue_Pocket_Neogeo#7]
Some of the audio layers are missing from certain games, eg. in the opening level of Metal Slug 2 the Arabic style instrumental layer isn't present. Other games have distortion for some audio elements, eg. Samurai Shodown 2.

**Comment by Mazamars312** [comment]
I am looking in to this. Working on the Graphics core, timing, Save games, backup ram, Autoloaders and some controller setups. Will arrange some time on this after 0.6.0 Alpha

**Comment by Mazamars312** [comment]
Have fixed this in version 0.6.0- alpha. this was a masking issue that I had not worked out correctly in the first build. Releasing very soon :-)
