### ISSUE TITLE
Using the data index

### ISSUE THREAD

**Issue by jotego** [Mazamars312/Analogue_Pocket_Neogeo#8]
I'd like to ask you about whether you considered using the data region indexes at all:

https://github.com/Mazamars312/Analogue_Pocket_Neogeo/blob/d8f58ab95c774260f9602e53d9e03cdf99a86ccf/dist/Cores/Mazamars312.NeoGeo/data.json#L8

Your code seems to distinguish each part of the data by an address. Didn't the index provide any benefit? 

Just out of curiosity. Thanks for your time.

**Comment by Mazamars312** [comment]
No Problem Mate,

Ive been meaning to chat to you soon on the audio side of things as well. 

Right now Im only using the indexs for the instance.json data loading with multiple roms. I would like to get the indexing in the core itself going very soon thou. 

If you want I can show how this works with the framework. Once I get things working much better in the Neogeo I will look in to doing this as well so people can plugin their cores with no issues using the same indexes between frameworks.

A brief write up on this on what happens in the core side. When looking at the core_bridge_cmd, when the dataslot_requestread/write wire goes high for a clock cycle the index(dataslot_requestread/write_id) is registered then. After that both the dataslot_requestread/write_ack and dataslot_requestread/write_ok has to be high advising that that index is ready to accept data.

Here is an example of the Instance.json that terminator2k2 made for every game for me so far so you can get a idea on multi-rom loads as well :-) Big thanks to him on this
[Metal Slug 2.json.txt](https://github.com/Mazamars312/Analogue_Pocket_Neogeo/files/9277637/Metal.Slug.2.json.txt)

you can hit me up on discord if you wish.
